channels:
- bioconda
- conda-forge
- defaults
dependencies:
- bioconductor-ebimage=4.13.*
- maven=3.5.*
- openjdk=8.0.*
- r-assertthat=0.2.*
# https://github.com/ContinuumIO/anaconda-issues/issues/4656
- r-base=3.4.*
- r-devtools=1.13.*
- r-git2r=0.19.*
- r-httr=1.3.*
- r-irdisplay=0.4.*
- r-irkernel=0.8.*
- r-jpeg=0.1_8
- r-repr=0.13
- r-rjava=0.9_8
- r-roxygen2=6.0.*
- r-testthat=1.0.*
- r-tidyverse=1.1.*
- r-xml2=1.1.*
- r-getpass=0.2.*
prefix: /opt/conda/envs/r-omero
